name: 'Cauchy-poisson-s=0.1'
dim: 2
gridpts: 30
key: 641

train:
  opt_steps: 0
  diagnostics_interval: 1
  truth:
      id: 'poisson-exA'
      noise: 0.01
  samples:
    N: 1000
    dist: 'uniform'
  reg:
    PINN: [1, 1, 1]
    DATA: [2, 40, 50]

model:
  kernel:
    id: "Cauchy"
    variance: 1
