name: 'DenseNN-poisson-smallnet'
dim: 2
gridpts: 30
key: 641

train:
  opt:
    id: 'adam'
    steps: 10000
    lr: 0.0001
  diagnostics:
    gen_every: 10
    pile_every: 1000
  truth:
      id: 'poisson-exA'
      noise: 0.01
  samples:
    N: 1000
    dist: 'uniform'
  reg:
    PINN: [0.01, 10000, 12]
    DATA: [0.01, 10, 12]

model:
  id: "mlp"
  dims: [2, 256, 256, 1]

