name: 'DenseNNm-poisson'
dim: 2
gridpts: 30
key: 641

train:
  opt:
    id: 'adam'
    steps: 10001
    lr: 0.0001
  diagnostics:
    gen_every: 100
    pile_every: 1000
  truth:
      id: 'poisson-exA'
      noise: 0.5
  samples:
    N: 50
    dist: 'uniform'
  reg:
    PINN: [1, 1, 1]
    DATA: [0.4, 0.6, 5]

model:
  id: "mlp"
  dims: [2, 64, 64, 64, 1]

