name: 'DenseNN-poisson-smallnet-test-4'
dim: 2
gridpts: 30
key: 641

train:
  opt:
    id: 'adam'
    steps: 500
    lr: 0.0001
  diagnostics:
    gen_every: 10
    pile_every: 20
  truth:
      id: 'poisson-exA'
      noise: 0.1
  samples:
    N: 50
    dist: 'uniform'
  reg:
    PINN: [1, 1, 1]
    DATA: [1500, 1500, 1]

model:
  id: "mlp"
  dims: [2, 256, 256, 1]

