name: 'MLP-lg-no'
dim: 2
gridpts: 30
key: 641

train:
  opt:
    id: 'adam'
    steps: 10001
    lr: 0.0001
  diagnostics:
    gen_every: 100
    pile_every: 1000
  truth:
      id: 'poisson-exA'
      noise: 1
  samples:
    N: 200
    dist: 'uniform'
    with_boundary: True
  reg:
    PINN: [1, 1, 1]
    DATA: [0.005, 0.15, 5]

model:
  id: "mlp"
  dims: [2, 128, 128, 1]

