name: 'RBF-md-cl'
dim: 2
gridpts: 30
key: 641

train:
  opt:
    steps: 0
  truth:
      id: 'poisson-exA'
      noise: 0.01
  samples:
    N: 1000
    dist: 'uniform'
  reg:
    PINN: [1, 1, 1]
    DATA: [8, 12, 5]

model:
  id: "RBF"
  bandwidth: 0.25

