name: 'RBF-md-no'
dim: 2
gridpts: 30
key: 641

train:
  opt:
    steps: 0
  truth:
      id: 'poisson-exA'
      noise: 1
  samples:
    N: 200
    dist: 'uniform'
  reg:
    PINN: [0.5, 2, 5]
    DATA: [0.5, 2, 5]

model:
  id: "RBF"
  bandwidth: 0.25

