name: 'RBF-sm-cl'
dim: 2
gridpts: 30
key: 641

train:
  opt:
    steps: 0
  truth:
      id: 'poisson-exA'
      noise: 0.01
  samples:
    N: 200
    dist: 'uniform'
  reg:
    PINN: [0.01, 10, 5]
    DATA: [0.01, 10, 5]

model:
  id: "RBF"
  bandwidth: 0.025

